server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none

logging.level:
  org.hibernate.SQL: debug

logging-module:
  version: 0.0.0

api:
  version: 1.0.0
