server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create

logging.level:
  org.hibernate.SQL: debug

logging-module:
  version: 0.0.0

api:
  version: 1.0.0
