server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create

logging.level:
  org.hibernate.SQL: debug

logging-module:
  version: 0.0.0

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 5

payment:
  secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  connection-timeout-seconds: 10
  read-timeout-seconds: 30
  base-url: https://api.tosspayments.com
